
<?php $usbkeys =  array(

    array(
        "name" => "Sandisk RedDrive 1000",
        "image" => "img/a.png",
        "text" => "Sandisk's hot new flash drive combines excellent speed and accuracy.",
        "data-target" => "a",
        "size" => "16",
        "price" => "32",
        "modalText" => "Cutting edge super-flash technology makes Sandisk's RedDrive 1000 one of the hottest drives on the market.",
    ),
    array(
        "name" => "SP Key",
        "image" => "img/b.png",
        "text" => "The SP Key will hold all of your important data for the long run... and in style!",
        "data-target" => "b",
        "size" => "32",
        "price" => "45",
        "modalText" => "Cutting edge super-flash technology makes the SP Key one of the hottest drives on the market.",
    ),
    array(
        "name" => "Samsung Arrow",
        "image" => "img/c.png",
        "text" => "Perfect for images or documents, Samsung has done it again.",
        "data-target" => "c",
        "size" => "32",
        "price" => "52",
        "modalText" => "Cutting edge super-flash technology makes the Samsung Arrow one of the hottest drives on the market.",
    ),
    array(
        "name" => "SanDisk Button",
        "image" => "img/d.png",
        "text" => "So small and unimposing, you might even forget it's in your pocket!",
        "data-target" => "d",
        "size" => "8",
        "price" => "19",
        "modalText" => "Cutting edge super-flash technology makes the SanDisk Button one of the hottest drives on the market.",
    ),
    array(
        "name" => "Transformer",
        "image" => "img/e.png",
        "text" => "From a bottle-opener to a door-stop, this little flash drive can do almost anything.",
        "data-target" => "e",
        "size" => "32",
        "price" => "49",
        "modalText" => "Cutting edge super-flash technology makes the Transformer one of the hottest drives on the market.",
    ),
    array(
        "name" => "Samsung Silver",
        "image" => "img/f.png",
        "text" => "Luxury meets elegance in Samsung's high-end model You get what you pay for!",
        "data-target" => "f",
        "size" => "64",
        "price" => "72",
        "modalText" => "Cutting edge super-flash technology makes the Samsung Silver one of the hottest drives on the market.",
    ),
    array(
        "name" => "Thetis Key",
        "image" => "img/g.png",
        "text" => "The flagship drive from upcoming Greek manufacturer Thetis. Now Fido certified.",
        "data-target" => "g",
        "size" => "32",
        "price" => "64",
        "modalText" => "Cutting edge super-flash technology makes the Thetis Key one of the hottest drives on the market.",
    ),
    array(
        "name" => "PNY Gadget",
        "image" => "img/h.png",
        "text" => "Designed from Leonardo da Vinci's sketches, the Gadget is a true work of art.",
        "data-target" => "h",
        "size" => "32",
        "price" => "45",
        "modalText" => "Cutting edge super-flash technology makes the PNY Gadget one of the hottest drives on the market.",
    ),
    array(
        "name" => "iLOK Performer",
        "image" => "img/i.png",
        "text" => "The iLOK Performer locks your data so thoroughly that even you can't get to it!",
        "data-target" => "i",
        "size" => "16",
        "price" => "40",
        "modalText" => "Cutting edge super-flash technology makes the iLOK Performer one of the hottest drives on the market.",
    ),
    array(
        "name" => "Corsair Voyager Vega",
        "image" => "img/j.png",
        "text" => "The preferred flash drive of corsairs and mercenaries for over 5 centuries.",
        "data-target" => "j",
        "size" => "24",
        "price" => "86",
        "modalText" => "Cutting edge super-flash technology makes the Corsair Voyager Vega one of the hottest drives on the market.",
    ),
    array(
        "name" => "Samsung Little Boy",
        "image" => "img/k.png",
        "text" => "Don't let the size fool you! The Little Boy has the power of an adult!",
        "data-target" => "k",
        "size" => "128",
        "price" => "119",
        "modalText" => "Cutting edge super-flash technology makes the Little Boy one of the hottest drives on the market.",
    ),
    array(
        "name" => "Corsair GS",
        "image" => "img/l.png",
        "text" => "Waterproof, weatherproof, fireproof... everything but childproof!",
        "data-target" => "l",
        "size" => "8",
        "price" => "12",
        "modalText" => "Cutting edge super-flash technology makes the Corsair GS one of the hottest drives on the market.",
    )

);

?>
