<?php


$books = [
    ['image' => 'img/couv_bathroom.png',
     'bookTitle' => 'Bathroom Manners',
     'bookAuthor' => 'Textes de Jean-Claude Kauffman',
     'price' => '26 €',
     'bookYear' => '2006',
     'bookPage' => '32 pages',
     'bookShaping' => 'Broché, jaquette',
     'bookSize' => '200 x 300 mm',
     'bookResume' => 'Bathroom Manners réunit des photographies prises dans des salles de bains par des photographes inspirés.',
     'dataTarget' => 'modal_1',
    ],

   ['image' =>'img/couv_realite.png',
    'bookTitle' => '+ de réalités',
    'bookAuthor' => 'École des Beaux-Arts de Nantes-Métropole',
    'price' => '16 €',
    'bookYear' => '2009',
    'bookPage' => '256 pages',
    'bookShaping' => 'Broché avec jaquette',
    'bookSize' => '210 x 270 mm',
    'bookResume' => '+ de Réalités présente le travail du groupe de recherche Abstractions de l’école supérieure des beaux-arts de Nantes Métropole et constitue la suite de l’exposition éponyme qui s’est tenue au Hangar à Bananes, à Nantes, en 2008.',
    'dataTarget' => 'modal_2',
   ],

   ['image' => 'img/couv_OLcoll.png',
    'bookTitle' => 'Ouest-Lumière – La Collection',
    'bookAuthor' => 'Yann Toma',
    'price' => '28 €',
    'bookYear' => '2008',
    'bookPage' => '400 pages',
    'bookShaping' => 'Broché, couverture en carton plume',
    'bookSize' => '200 x 280 mm',
    'bookResume' => 'Réalisé à l\'occasion de l\'exposition de Yann Toma au Musée Electropolis à Mulhouse, cet ouvrage est plus qu\'un catalogue. Il constitue une archive formidable de la société Ouest-Lumière au travers d\'objets et de schémas électriques ; tous légués par les actionnaires et les abonnés.',
    'dataTarget' => 'modal_3',
   ],

   ['image' => 'img/couv_oxymoriques.png',
    'bookTitle' => 'Oxymoriques',
    'bookAuthor' => 'Bettina Rheims et Michel Onfray',
    'price' => '14 €',
    'bookYear' => '2004',
    'bookPage' => '48 pages',
    'bookShaping' => 'Broché',
    'bookSize' => '140 x 190 mm',
    'bookResume' => 'La confrontation entre deux grands acteurs de la vie culturelle, à la fois contestataires et contestés... Philosophe et essayiste, Michel Onfray analyse la nature des photographies de Bettina Rheims, et développe la thèse d’un travail qui, plus que scandaleux ou sulfureux, expose des troubles.',
    'dataTarget' => 'modal_4',
   ],

   ['image' => 'img/couv_picasso.png',
    'bookTitle' => 'Critiques hostiles à Picasso',
    'bookAuthor' => '',
    'price' => '9,80 €',
    'bookYear' => '2000',
    'bookPage' => '48 pages',
    'bookShaping' => 'Broché, jaquette',
    'bookSize' => '135 x 230 mm',
    'bookResume' => 'Sélection de critiques, railleries et autres jugements défavorables parus dans la presse écrite, française et étrangère de 1917 à 1973 sur un des artistes les plus importants du XXe siècle. Les conformistes et les sceptiques se déchaînent en étalant leur étroitesse de perception.',
    'dataTarget' => 'modal_5',
   ],

   ['image' => 'img/couv_yann-toma.png',
    'bookTitle' => 'Yann Toma – Monographie',
    'bookAuthor' => 'Yann Toma',
    'price' => '32 €',
    'bookYear' => '2011',
    'bookPage' => '400 pages',
    'bookShaping' => 'Broché, 672 illustrations',
    'bookSize' => '280 x 280 mm',
    'bookResume' => 'La démarche artistique de Yann Toma débute il y a dix-neuf ans par la récupération d’éléments d’archives de l\'ancienne compagnie d\'électricité Ouest-Lumière. Il s\'approprie ainsi un réseau symbolique, une infrastructure usinière dont il a fait son territoire de recherche et la matière même de son activité artistique.',
    'dataTarget' => 'modal_6',
   ],

   ['image' => 'img/couv_kentridge.png',
    'bookTitle' => 'Stop Here',
    'bookAuthor' => 'William Kentridge',
    'price' => '12 €',
    'bookYear' => '20016',
    'bookPage' => '48 pages',
    'bookShaping' => 'Broché sous jaquette',
    'bookSize' => '125 x 210 mm',
    'bookResume' => 'Stop Here est écrit et dessiné au stylo plume. La figure de l’arbre est au cœur de ce livre. On y retrouve les codes d’expression propres à l’artiste',
    'dataTarget' => 'modal_7',
   ],

   ['image' => 'img/couv_leparc.png',
    'bookTitle' => 'Paroles de voleurs',
    'bookAuthor' => 'Julio Le Parc',
    'price' => '12 €',
    'bookYear' => '2010',
    'bookPage' => '48 pages',
    'bookShaping' => 'Broché sous jaquette',
    'bookSize' => '125 x 210 mm',
    'bookResume' => 'Artiste engagé, Julio le Parc prend part en 1960 à la fondation du GRAV (Groupe de recherche d’art visuel), qui concrétise, donne forme, organise et développe la confrontation des idées et expériences des onze artistes qu’il regroupe.',
    'dataTarget' => 'modal_8',
   ],

   ['image' => 'img/couv_kounellis.png',
    'bookTitle' => 'La Perdita del punto di vista',
    'bookAuthor' => 'Jannis Kounellis',
    'price' => '12 €',
    'bookYear' => '2008',
    'bookPage' => '48 pages',
    'bookShaping' => 'Broché sous jaquette',
    'bookSize' => '125 x 210 mm',
    'bookResume' => 'L\'esprit provocateur qui anime toute l’œuvre de Jannis Kounellis est une fois de plus exprimé dans La Perdita del punto di vista. Le membre le plus radical de l’Arte povera s’interroge sur la brièveté de la vie et l’impossibilité de la peindre tout entière, nous entraînant dans un voyage au travers de la mythologie, des civilisations antiques et de sa propre interrogation artistique.',
    'dataTarget' => 'modal_9',
   ],

   ['image' => 'img/couv_miralda.png',
    'bookTitle' => 'KM',
    'bookAuthor' => 'Antoni Miralda',
    'price' => '12 €',
    'bookYear' => '2010',
    'bookPage' => '48 pages',
    'bookShaping' => 'Broché sous jaquette',
    'bookSize' => '125 x 210 mm',
    'bookResume' => 'Dans KM (Ketchup-Moutarde), ouvrage bilingue français/catalan, Antoni Miralda revient sur son parcours — des petits soldats en plastique aux expériences culinaires.',
    'dataTarget' => 'modal_10',
   ],

   ['image' => 'img/couv_orlan.png',
    'bookTitle' => 'Pomme-cul et petite fleurs',
    'bookAuthor' => 'ORLAN',
    'price' => '12 €',
    'bookYear' => '2004',
    'bookPage' => '48 pages',
    'bookShaping' => 'Broché sous jaquette',
    'bookSize' => '125 x 210 mm',
    'bookResume' => 'Sans la poésie, l’œuvre d’ORLAN ne serait pas complète. Pomme-cul et Petites fleurs, met en évidence un autre aspect de son talent sulfureux et détonnant qu’elle a appelé « L’Art charnel ». Depuis les années 1960, ORLAN n’a cessé de juxtaposer, chaque jours, des mots, des lignes, des poèmes, aux côtés des listes de travail et des courriers formels.',
    'dataTarget' => 'modal_11',
   ],

   ['image' => 'img/couv_scurti.png',
    'bookTitle' => 'Sept à sept',
    'bookAuthor' => 'Franck Scurti',
    'price' => '12 €',
    'bookYear' => '2005',
    'bookPage' => '48 pages',
    'bookShaping' => 'Broché sous jaquette',
    'bookSize' => '125 x 210 mm',
    'bookResume' => 'Si l’on pouvait lui dégager une paternité, Franck Scurti, se réclamerait de Picabia, Raymond Hains, Marcel Broodthaers, Jacques Tati ou Francis Ponge qui lui a «&nbsp;appris à regarder les objets, à les analyser, à les perdre en eux-mêmes, puis à les réévaluer&nbsp;».',
    'dataTarget' => 'modal_12',
   ],

];

